-- AlterTable
ALTER TABLE "Location" ADD COLUMN "placeId" TEXT;
ALTER TABLE "Location" ADD COLUMN "lat" DOUBLE PRECISION;
ALTER TABLE "Location" ADD COLUMN "lng" DOUBLE PRECISION;
ALTER TABLE "Location" ADD COLUMN "verified" BOOLEAN NOT NULL DEFAULT false;
