/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as FindRouteImport } from './routes/find'
import { Route as ForClubsRouteImport } from './routes/for-clubs'
import { Route as ForCoachesRouteImport } from './routes/for-coaches'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SRouteImport } from './routes/s'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimZhangRouteImport } from './routes/tim-zhang'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known/apple-app-site-association'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known/assetlinks[.]json'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAssistantRouteImport } from './routes/app/assistant'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppBookingsRouteImport } from './routes/app/bookings'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppImportRouteImport } from './routes/app/import'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppMoreRouteImport } from './routes/app/more'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppScheduleRouteImport } from './routes/app/schedule'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSetupRouteImport } from './routes/app/setup'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageAccountRouteImport } from './routes/manage.account'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AppClientsIdRouteImport } from './routes/app/clients.$id'
import { Route as AppLessonsIdRouteImport } from './routes/app/lessons.$id'
import { Route as AppMessagesIndexRouteImport } from './routes/app/messages.index'
import { Route as AppMessagesClientIdRouteImport } from './routes/app/messages.$clientId'
import { Route as AppMoreAccountRouteImport } from './routes/app/more.account'
import { Route as AppMoreAssistantRouteImport } from './routes/app/more.assistant'
import { Route as AppMoreHoursRouteImport } from './routes/app/more.hours'
import { Route as AppMoreLocationsRouteImport } from './routes/app/more.locations'
import { Route as AppMorePaymentsRouteImport } from './routes/app/more.payments'
import { Route as AppSeriesIdRouteImport } from './routes/app/series.$id'
import { Route as ManageMessagesIndexRouteImport } from './routes/manage.messages.index'
import { Route as ManageMessagesCoachIdRouteImport } from './routes/manage.messages.$coachId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClubsRoute = ForClubsRouteImport.update({
  id: '/for-clubs',
  path: '/for-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCoachesRoute = ForCoachesRouteImport.update({
  id: '/for-coaches',
  path: '/for-coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SRoute = SRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimZhangRoute = TimZhangRouteImport.update({
  id: '/tim-zhang',
  path: '/tim-zhang',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageAccountRoute = ManageAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ManageRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppLessonsIdRoute = AppLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppMessagesClientIdRoute = AppMessagesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppMoreAccountRoute = AppMoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreAssistantRoute = AppMoreAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreHoursRoute = AppMoreHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreLocationsRoute = AppMoreLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMorePaymentsRoute = AppMorePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppSeriesIdRoute = AppSeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => AppRoute,
} as any)
const ManageMessagesIndexRoute = ManageMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageMessagesCoachIdRoute = ManageMessagesCoachIdRouteImport.update({
  id: '/messages/$coachId',
  path: '/messages/$coachId',
  getParentRoute: () => ManageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/confirmed': typeof ConfirmedRoute
  '/delete-account': typeof DeleteAccountRoute
  '/find': typeof FindRoute
  '/for-clubs': typeof ForClubsRoute
  '/for-coaches': typeof ForCoachesRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRouteWithChildren
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/s': typeof SRoute
  '/sign-in': typeof SignInRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/tim-zhang': typeof TimZhangRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/import': typeof AppImportRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/more': typeof AppMoreRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/book/$slug': typeof BookSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/manage/account': typeof ManageAccountRoute
  '/r/$token': typeof RTokenRoute
  '/app/': typeof AppIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/lessons/$id': typeof AppLessonsIdRoute
  '/app/messages/$clientId': typeof AppMessagesClientIdRoute
  '/app/more/account': typeof AppMoreAccountRoute
  '/app/more/assistant': typeof AppMoreAssistantRoute
  '/app/more/hours': typeof AppMoreHoursRoute
  '/app/more/locations': typeof AppMoreLocationsRoute
  '/app/more/payments': typeof AppMorePaymentsRoute
  '/app/series/$id': typeof AppSeriesIdRoute
  '/manage/messages/$coachId': typeof ManageMessagesCoachIdRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/manage/messages/': typeof ManageMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/confirmed': typeof ConfirmedRoute
  '/delete-account': typeof DeleteAccountRoute
  '/find': typeof FindRoute
  '/for-clubs': typeof ForClubsRoute
  '/for-coaches': typeof ForCoachesRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/s': typeof SRoute
  '/sign-in': typeof SignInRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/tim-zhang': typeof TimZhangRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/import': typeof AppImportRoute
  '/app/more': typeof AppMoreRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/book/$slug': typeof BookSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/manage/account': typeof ManageAccountRoute
  '/r/$token': typeof RTokenRoute
  '/app': typeof AppIndexRoute
  '/manage': typeof ManageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/lessons/$id': typeof AppLessonsIdRoute
  '/app/messages/$clientId': typeof AppMessagesClientIdRoute
  '/app/more/account': typeof AppMoreAccountRoute
  '/app/more/assistant': typeof AppMoreAssistantRoute
  '/app/more/hours': typeof AppMoreHoursRoute
  '/app/more/locations': typeof AppMoreLocationsRoute
  '/app/more/payments': typeof AppMorePaymentsRoute
  '/app/series/$id': typeof AppSeriesIdRoute
  '/manage/messages/$coachId': typeof ManageMessagesCoachIdRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/manage/messages': typeof ManageMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/confirmed': typeof ConfirmedRoute
  '/delete-account': typeof DeleteAccountRoute
  '/find': typeof FindRoute
  '/for-clubs': typeof ForClubsRoute
  '/for-coaches': typeof ForCoachesRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRouteWithChildren
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/s': typeof SRoute
  '/sign-in': typeof SignInRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/tim-zhang': typeof TimZhangRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/import': typeof AppImportRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/more': typeof AppMoreRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/book/$slug': typeof BookSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/manage/account': typeof ManageAccountRoute
  '/r/$token': typeof RTokenRoute
  '/app/': typeof AppIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/lessons/$id': typeof AppLessonsIdRoute
  '/app/messages/$clientId': typeof AppMessagesClientIdRoute
  '/app/more/account': typeof AppMoreAccountRoute
  '/app/more/assistant': typeof AppMoreAssistantRoute
  '/app/more/hours': typeof AppMoreHoursRoute
  '/app/more/locations': typeof AppMoreLocationsRoute
  '/app/more/payments': typeof AppMorePaymentsRoute
  '/app/series/$id': typeof AppSeriesIdRoute
  '/manage/messages/$coachId': typeof ManageMessagesCoachIdRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/manage/messages/': typeof ManageMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/app'
    | '/confirmed'
    | '/delete-account'
    | '/find'
    | '/for-clubs'
    | '/for-coaches'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/manage'
    | '/preview'
    | '/pricing'
    | '/s'
    | '/sign-in'
    | '/start'
    | '/terms'
    | '/tim-zhang'
    | '/welcome'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/app/assistant'
    | '/app/billing'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/clients'
    | '/app/import'
    | '/app/messages'
    | '/app/more'
    | '/app/payments'
    | '/app/schedule'
    | '/app/settings'
    | '/app/setup'
    | '/book/$slug'
    | '/c/$slug'
    | '/manage/account'
    | '/r/$token'
    | '/app/'
    | '/manage/'
    | '/api/auth/$'
    | '/api/cron/reminders'
    | '/api/stripe/webhook'
    | '/app/clients/$id'
    | '/app/lessons/$id'
    | '/app/messages/$clientId'
    | '/app/more/account'
    | '/app/more/assistant'
    | '/app/more/hours'
    | '/app/more/locations'
    | '/app/more/payments'
    | '/app/series/$id'
    | '/manage/messages/$coachId'
    | '/app/messages/'
    | '/manage/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/confirmed'
    | '/delete-account'
    | '/find'
    | '/for-clubs'
    | '/for-coaches'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/preview'
    | '/pricing'
    | '/s'
    | '/sign-in'
    | '/start'
    | '/terms'
    | '/tim-zhang'
    | '/welcome'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/app/assistant'
    | '/app/billing'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/clients'
    | '/app/import'
    | '/app/more'
    | '/app/payments'
    | '/app/schedule'
    | '/app/settings'
    | '/app/setup'
    | '/book/$slug'
    | '/c/$slug'
    | '/manage/account'
    | '/r/$token'
    | '/app'
    | '/manage'
    | '/api/auth/$'
    | '/api/cron/reminders'
    | '/api/stripe/webhook'
    | '/app/clients/$id'
    | '/app/lessons/$id'
    | '/app/messages/$clientId'
    | '/app/more/account'
    | '/app/more/assistant'
    | '/app/more/hours'
    | '/app/more/locations'
    | '/app/more/payments'
    | '/app/series/$id'
    | '/manage/messages/$coachId'
    | '/app/messages'
    | '/manage/messages'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/app'
    | '/confirmed'
    | '/delete-account'
    | '/find'
    | '/for-clubs'
    | '/for-coaches'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/manage'
    | '/preview'
    | '/pricing'
    | '/s'
    | '/sign-in'
    | '/start'
    | '/terms'
    | '/tim-zhang'
    | '/welcome'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/app/assistant'
    | '/app/billing'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/clients'
    | '/app/import'
    | '/app/messages'
    | '/app/more'
    | '/app/payments'
    | '/app/schedule'
    | '/app/settings'
    | '/app/setup'
    | '/book/$slug'
    | '/c/$slug'
    | '/manage/account'
    | '/r/$token'
    | '/app/'
    | '/manage/'
    | '/api/auth/$'
    | '/api/cron/reminders'
    | '/api/stripe/webhook'
    | '/app/clients/$id'
    | '/app/lessons/$id'
    | '/app/messages/$clientId'
    | '/app/more/account'
    | '/app/more/assistant'
    | '/app/more/hours'
    | '/app/more/locations'
    | '/app/more/payments'
    | '/app/series/$id'
    | '/manage/messages/$coachId'
    | '/app/messages/'
    | '/manage/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  ConfirmedRoute: typeof ConfirmedRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  FindRoute: typeof FindRoute
  ForClubsRoute: typeof ForClubsRoute
  ForCoachesRoute: typeof ForCoachesRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  ManageRoute: typeof ManageRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  PricingRoute: typeof PricingRoute
  SRoute: typeof SRoute
  SignInRoute: typeof SignInRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  TimZhangRoute: typeof TimZhangRoute
  WelcomeRoute: typeof WelcomeRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  BookSlugRoute: typeof BookSlugRoute
  CSlugRoute: typeof CSlugRoute
  RTokenRoute: typeof RTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clubs': {
      id: '/for-clubs'
      path: '/for-clubs'
      fullPath: '/for-clubs'
      preLoaderRoute: typeof ForClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-coaches': {
      id: '/for-coaches'
      path: '/for-coaches'
      fullPath: '/for-coaches'
      preLoaderRoute: typeof ForCoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s': {
      id: '/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof SRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-zhang': {
      id: '/tim-zhang'
      path: '/tim-zhang'
      fullPath: '/tim-zhang'
      preLoaderRoute: typeof TimZhangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/account': {
      id: '/manage/account'
      path: '/account'
      fullPath: '/manage/account'
      preLoaderRoute: typeof ManageAccountRouteImport
      parentRoute: typeof ManageRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients/$id': {
      id: '/app/clients/$id'
      path: '/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/lessons/$id': {
      id: '/app/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/app/lessons/$id'
      preLoaderRoute: typeof AppLessonsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/app/messages/$clientId': {
      id: '/app/messages/$clientId'
      path: '/$clientId'
      fullPath: '/app/messages/$clientId'
      preLoaderRoute: typeof AppMessagesClientIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/app/more/account': {
      id: '/app/more/account'
      path: '/account'
      fullPath: '/app/more/account'
      preLoaderRoute: typeof AppMoreAccountRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/app/more/assistant': {
      id: '/app/more/assistant'
      path: '/assistant'
      fullPath: '/app/more/assistant'
      preLoaderRoute: typeof AppMoreAssistantRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/app/more/hours': {
      id: '/app/more/hours'
      path: '/hours'
      fullPath: '/app/more/hours'
      preLoaderRoute: typeof AppMoreHoursRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/app/more/locations': {
      id: '/app/more/locations'
      path: '/locations'
      fullPath: '/app/more/locations'
      preLoaderRoute: typeof AppMoreLocationsRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/app/more/payments': {
      id: '/app/more/payments'
      path: '/payments'
      fullPath: '/app/more/payments'
      preLoaderRoute: typeof AppMorePaymentsRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/app/series/$id': {
      id: '/app/series/$id'
      path: '/series/$id'
      fullPath: '/app/series/$id'
      preLoaderRoute: typeof AppSeriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/manage/messages/': {
      id: '/manage/messages/'
      path: '/messages'
      fullPath: '/manage/messages/'
      preLoaderRoute: typeof ManageMessagesIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/messages/$coachId': {
      id: '/manage/messages/$coachId'
      path: '/messages/$coachId'
      fullPath: '/manage/messages/$coachId'
      preLoaderRoute: typeof ManageMessagesCoachIdRouteImport
      parentRoute: typeof ManageRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppMessagesRouteChildren {
  AppMessagesClientIdRoute: typeof AppMessagesClientIdRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesClientIdRoute: AppMessagesClientIdRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppMoreRouteChildren {
  AppMoreAccountRoute: typeof AppMoreAccountRoute
  AppMoreAssistantRoute: typeof AppMoreAssistantRoute
  AppMoreHoursRoute: typeof AppMoreHoursRoute
  AppMoreLocationsRoute: typeof AppMoreLocationsRoute
  AppMorePaymentsRoute: typeof AppMorePaymentsRoute
}

const AppMoreRouteChildren: AppMoreRouteChildren = {
  AppMoreAccountRoute: AppMoreAccountRoute,
  AppMoreAssistantRoute: AppMoreAssistantRoute,
  AppMoreHoursRoute: AppMoreHoursRoute,
  AppMoreLocationsRoute: AppMoreLocationsRoute,
  AppMorePaymentsRoute: AppMorePaymentsRoute,
}

const AppMoreRouteWithChildren =
  AppMoreRoute._addFileChildren(AppMoreRouteChildren)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppImportRoute: typeof AppImportRoute
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppMoreRoute: typeof AppMoreRouteWithChildren
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLessonsIdRoute: typeof AppLessonsIdRoute
  AppSeriesIdRoute: typeof AppSeriesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppBillingRoute: AppBillingRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppImportRoute: AppImportRoute,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppMoreRoute: AppMoreRouteWithChildren,
  AppPaymentsRoute: AppPaymentsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
  AppLessonsIdRoute: AppLessonsIdRoute,
  AppSeriesIdRoute: AppSeriesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ManageRouteChildren {
  ManageAccountRoute: typeof ManageAccountRoute
  ManageIndexRoute: typeof ManageIndexRoute
  ManageMessagesCoachIdRoute: typeof ManageMessagesCoachIdRoute
  ManageMessagesIndexRoute: typeof ManageMessagesIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageAccountRoute: ManageAccountRoute,
  ManageIndexRoute: ManageIndexRoute,
  ManageMessagesCoachIdRoute: ManageMessagesCoachIdRoute,
  ManageMessagesIndexRoute: ManageMessagesIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  ConfirmedRoute: ConfirmedRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  FindRoute: FindRoute,
  ForClubsRoute: ForClubsRoute,
  ForCoachesRoute: ForCoachesRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  ManageRoute: ManageRouteWithChildren,
  PreviewRoute: PreviewRoute,
  PricingRoute: PricingRoute,
  SRoute: SRoute,
  SignInRoute: SignInRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  TimZhangRoute: TimZhangRoute,
  WelcomeRoute: WelcomeRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  BookSlugRoute: BookSlugRoute,
  CSlugRoute: CSlugRoute,
  RTokenRoute: RTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
